In [2]:
import numpy as np

## Numpy array

In [3]:
benimlistem=[20,30,40]

In [4]:
type(benimlistem)

list

In [5]:
np.array(benimlistem)

array([20, 30, 40])

In [6]:
type(np.array(benimlistem))

numpy.ndarray

In [7]:
matrixlistesi=[[10,20,30],[20,30,40],[30,40,50]]

In [8]:
matrixlistesi[0][1]

20

In [9]:
np.array(matrixlistesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [16]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [22]:
np.random.randn(8,8)

array([[-1.45367142,  0.45312543, -0.97616562, -1.75944918,  0.26155956,
        -0.12172924, -0.14892685, -2.68008798],
       [ 1.72068002,  1.01213747, -0.60060247, -0.31734496,  0.63247599,
        -1.02827731,  0.13146421,  1.07670342],
       [-0.70500158, -0.63284181,  0.69032669, -1.590755  ,  0.84219793,
        -1.92026212, -1.01641008,  0.28950078],
       [ 1.22115113,  0.69735454, -1.21908966,  0.34990157,  0.44796735,
        -0.45385778,  0.33119547,  0.50329366],
       [ 1.64759907, -0.27424852,  0.5614954 , -0.79763423, -0.52944237,
         0.25578669,  2.30085964,  1.5818669 ],
       [ 0.68819348, -0.18888445, -1.12203255,  1.72949975, -1.91702326,
         0.47131858,  0.93839643, -0.95689471],
       [ 0.10903654, -0.44278034,  0.84171156,  1.1800415 , -0.13726994,
        -0.18530356, -0.28927311,  1.30561408],
       [ 0.59701127,  0.00757747,  2.13118332,  1.54037303,  0.84428565,
        -0.3517721 ,  0.89508784, -0.35000302]])

In [29]:
np.random.randint(5,10)

8

In [33]:
np.random.randint(1,300,10)

array([225, 159,  79, 202, 102, 294,  19, 237, 154, 250])

In [34]:
benimnumpydizim=np.arange(0,30)

In [35]:
benimnumpydizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
benimrandomdizim=np.random.randint(0,400,20)

In [41]:
benimrandomdizim

array([139, 307,  87, 279, 275, 261, 150, 255, 189, 250,  77, 106, 320,
       237, 312,  62,  24, 286, 107, 364])

## numpy dizi methodları

In [43]:
benimnumpydizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
benimnumpydizim.max()

29

In [45]:
benimrandomdizim.max()

364

In [46]:
benimrandomdizim.min()

24

In [51]:
len(benimnumpydizim)

30

In [52]:
benimrandomdizim.argmax()

19

In [53]:
benimrandomdizim.argmin()

16

In [55]:
benimreshapedizim=benimnumpydizim.reshape(5,6)

In [56]:
benimreshapedizim.shape 

(5, 6)