In [1]:
import numpy as np

In [2]:
benimdizim=np.arange(0,15)

In [3]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimdizim[5]

5

In [6]:
benimdizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimdizim[3:8]=-5

In [8]:
benimdizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskadizi=np.arange(0,24)

In [10]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
silicingdizisi=baskadizi[4:9]

In [13]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
silicingdizisi[:]=-5

In [19]:
silicingdizisi

array([-5, -5, -5, -5, -5])

In [20]:
baskadizi

array([ 0,  1,  2,  3, -5, -5, -5, -5, -5,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekdizi=np.arange(0,24)

In [22]:
ornekdizikopyası=ornekdizi.copy()

In [23]:
ornekdizikopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
ornekdizislicingkopyası=ornekdizikopyası[3:6]

In [26]:
ornekdizislicingkopyası

array([3, 4, 5])

In [27]:
ornekdizislicingkopyası[:]=5

In [28]:
ornekdizikopyası

array([ 0,  1,  2,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [33]:
benimlistem=[[10,20,30],[40,50,60],[70,80,90]]
benimMatrixDizisi=np.array(benimlistem)

In [34]:
benimMatrixDizisi

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
benimMatrixDizisi[0]

array([10, 20, 30])

In [36]:
benimMatrixDizisi[1][2]

60

In [40]:
benimMatrixDizisi[1,2]

60

In [41]:
benimMatrixDizisi[1:,2]

array([60, 90])

In [43]:
benimMatrixDizisi[2:,2:]

array([[90]])

In [44]:
yenimatrix=np.arange(0,25).reshape(5,5)

In [45]:
yenimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
yenimatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [47]:
yenimatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [52]:
yenibirdizi=np.random.randint(0,100,20)

In [53]:
yenibirdizi

array([64, 12, 55, 87, 19, 31, 77, 69, 85, 51, 24, 94, 89, 35, 23, 61, 42,
       88, 10, 79])

In [58]:
sonucdizisi=yenibirdizi>24

In [59]:
sonucdizisi

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False,  True])

In [60]:
yenibirdizi

array([64, 12, 55, 87, 19, 31, 77, 69, 85, 51, 24, 94, 89, 35, 23, 61, 42,
       88, 10, 79])

In [61]:
yenibirdizi[sonucdizisi]

array([64, 55, 87, 31, 77, 69, 85, 51, 94, 89, 35, 61, 42, 88, 79])

In [62]:
sondizi=np.arange(0,24)

In [63]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
sondizi+sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [65]:
sondizi*sondizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [66]:
sondizi/sondizi # 0/0  is a problem

C:\Users\Hasan Özcan\AppData\Local\Temp\ipykernel_3624\2654503216.py:1: RuntimeWarning: invalid value encountered in divide
  sondizi/sondizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [67]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [68]:
np.max(sondizi)

23

In [69]:
np.min(sondizi)

0